### ISSUE TITLE
After having submitted a proposal, I'd expect the "+" to add another proposal

### ISSUE THREAD

**Issue by kariem** [GDGVienna/cfp-firebase#1]
The "+" button is shown next to a "list" (?) button after I have submitted a proposal

![talk-submitted](https://cloud.githubusercontent.com/assets/459324/15971171/289a6a10-2f38-11e6-92eb-619961973480.png)

I would expect the "+" button to add another proposal, instead it lets me edit the proposal I have. Similarily the "list" button opens a list of proposals with one title and offers an edit button there.

→ We could just show the edit button on this screen without the confusion.

**Comment by helmuthb** [comment]
It should behave as you described.
There is something wrong with how data is dealt with when editing. To be on the save side I have disabled the edit functionality for the moment.
So "List" icon shows existing proposals.
"Plus" icon allows adding a new one.
Existing proposals cannot be changed (at the moment).
