### ISSUE TITLE
Form on new CFP contains data from old proposal

### ISSUE THREAD

**Issue by kariem** [GDGVienna/cfp-firebase#2]
Steps to reproduce:
1. Add a proposal to the CFP for DevFest
2. Submit the proposal
3. Scroll down to the CFP for droidcon Vienna
4. Click the "+" button

Expected behavior: I can start with my proposal for the Droidcon CFP

Actual behavior: The form is already filled out with data previously entered for the DevFest CFP

**Comment by helmuthb** [comment]
Thanks for reporting this @kariem!

The submission of new proposals has been simplified and is now using clearing the form afterwards.
